### ISSUE TITLE
Couldn't get the Execute Plugin to work

### ISSUE THREAD

**Issue by pyed** [pecigonzalo/docker-deluge#10]
if you go to `WebUI Preferences -> Plugin` and check the `Execute` Plugin, you'll get a new side option called `Execute` that you can use to call scripts upon an event, so I have a bash script that contains the following:

``` bash
#!/bin/bash

# $2 should be the name of the torrent.
echo $2 >> /config/downloads.log
```

it lives in `/config/logscript.sh` with execute permissions.

in the plugin I added a new Event `Torrent Complete` and pointed it to `/config/logscript.sh`, but the script never gets called upon torrent completion, I'm not sure what might be the issue here.

The container overall works great, So thank you for making such quality containers!

**Comment by pyed** [comment]
it worked after restarting the container
`docker restart deluge`

**Comment by pecigonzalo** [comment]
Keep in mind this is now supported under the `linuxserver` group

**Comment by SHi-ON** [comment]
Just the essence of my 3 hours putting on this plugin to get it working:

* Execute plugin
    * path to the script: just the path without `python` command and any input arguments
        /opt/PyCharmProjects/DelugeExecute/execute_script.py
    * chown user:group to `deluge`
    * chmod 755
    * no need to restart deluge [at least in my case]
    * supports all three events. Try to test with Add event.
    * https://github.com/SHi-ON/DelugeExecute
    * see the [RHEL, CentOS] system log at `sudo tail -f /var/log/messages`
